name: TheClearProject
favicon: null
layout_spectrum: 0.25607
typography_spectrum: 0.8955412458162755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5ccffe'
    - '#000201'
    - '#397f9d'
    - '#27596d'
    - '#8fdcfe'
  brandStrength: 0.5
  lightness: 0.7209687184076756
  saturation: 0.26557953213341534
  rhythmicContrast: 0.1301828669384122
purpose: []
